---
- name: Obtain host certificate
  shell: echo -n | openssl s_client -connect {{ ar_os_common_cert_host }}:{{ ar_os_common_cert_port }} -servername {{ ar_os_common_cert_host }} -showcerts 2>/dev/null | sed --quiet '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
  changed_when: false
  register: certresult

- name: Save the certificate
  copy:
    dest: "{{ ar_os_common_cert_path }}"
    content: "{{ certresult.stdout }}"

- name: Get information on certificate
  openssl_certificate_info:
    path: "{{ ar_os_common_cert_path }}"
  register: certinfo

- name: Validate certificate
  assert:
    that:
      - not certinfo.expired
      - "certinfo.subject.commonName == '{{ ar_os_common_cert_host }}' or 'DNS:{{ ar_os_common_cert_host }}' in certinfo.subject_alt_name"
    msg: "Certificate must not be expired and must contain the hostname accessed in the subject commonName or subject alternate names"
