---
- name: Obtain host certificate
  shell: echo -n | openssl s_client -connect {{ ar_os_common_cert_host }}:{{ ar_os_common_cert_port }} -servername {{ ar_os_common_cert_host }} -showcerts 2>/dev/null | sed --quiet '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
  changed_when: false
  register: certresult

- name: Save the certificate
  copy:
    dest: "{{ ar_os_common_cert_path }}"
    content: "{{ certresult.stdout }}"

- include_tasks: validate-cert
  when: ansible_version.full is version('2.8.0', '>=')
