---
# Set vars for casl-ansible/roles/openshift-login
- name: Set facts for oc command line, openshift_user and openshift_login_url
  set_fact:
    openshift: { common: { client_binary: 'oc', admin_binary: 'oc' }}
    openshift_user: "{{ ar_os_common_openshift_username | default(ar_os_common_openshift_login_credentials[ar_os_common_openshift_login_url]['openshift_user']) }}"
    openshift_login_url: "{{ ar_os_common_openshift_login_url }}"

- name: "Assertions: ar_os_common (login basic assertions)"
  assert:
    that: "{{ ar_os_common_login_basic_assertions }}"

- name: "Assertions: ar_os_common (ar_os_common_openshift_login_credentials)"
  assert:
    that: "{{ ar_os_common_login_secret_map_assertions }}"
    msg: "{{ ar_os_common_login_secret_map_assertions_msg }}"
  when: not ar_os_common_openshift_password | length and not ar_os_common_openshift_token | length

- name: "Assertions: Credentials are provided"
  assert:
    that: "{{ ar_os_common_login_credential_assertions }}"
    msg: "{{ ar_os_common_login_secret_map_assertions_msg }}"

- name: Set fact for supplied openshift_password
  set_fact:
    openshift_password: "{{ ar_os_common_openshift_password }}"
  when: ar_os_common_openshift_password | length

- name: Set fact for default openshift_password
  set_fact:
    openshift_password: "{{ ar_os_common_openshift_login_credentials[ar_os_common_openshift_login_url].openshift_password }}"
  when: (not ar_os_common_openshift_password | length) and 'openshift_password' in ar_os_common_openshift_login_credentials[ar_os_common_openshift_login_url]

- name: Set fact for supplied openshift_token
  set_fact:
    openshift_token: "{{ ar_os_common_openshift_token }}"
  when: ar_os_common_openshift_token | length

- name: Set fact for default openshift_token
  set_fact:
    openshift_token: "{{ ar_os_common_openshift_login_credentials[ar_os_common_openshift_login_url].openshift_token }}"
  when: (not ar_os_common_openshift_token | length) and 'openshift_token' in ar_os_common_openshift_login_credentials[ar_os_common_openshift_login_url]

- debug:
    msg: "Logging into {{ ar_os_common_openshift_login_url }} as {{ openshift_user }}"

# Obtain currently logged in system
- shell: oc project | awk -F '"' '{print $(NF-1)}'
  register: current_host
  failed_when: false
  changed_when: false

# Vagary of casl-ansible/roles/openshift-login - have to empty the openshift_token if forcing another login
# which has to be done when logged into one cluster and requiring logging into another.
#   Check if the cluster we are logging into is the same as the one already logged into
- name: Force login when logging into another cluster
  set_fact:
    openshift_token: ''
  when: current_host.rc == 0 and current_host.stdout != ar_os_common_openshift_login_url and openshift_password is defined and openshift_password | trim != ''

#   Check if there is an override to force another login
- name: Force login override
  set_fact:
    openshift_token: ''
  when: ar_os_common_openshift_login_force and openshift_password is defined and openshift_password | trim != ''

- name: Favour token over password
  set_fact:
    openshift_password: ''
  when: (openshift_token is defined and openshift_token | length) and (openshift_password is defined and openshift_password | length)

# Do the login
- name: Include OpenShift Login role
  include_role:
    name: casl-ansible/roles/openshift-login

- debug:
    msg: "Logged into {{ ar_os_common_openshift_login_url }}"
