---
- name: Copy templates to desired location
  copy:
    src: "{{ item }}"
    dest: "{{ ar_os_common_dest }}/{{ item | basename }}"
  with_fileglob:
    - "{{ role_path }}/files/*"
  when: ar_os_common_selection is not defined

- name: Copy selected templates to desired location
  copy:
    src: "{{ item }}"
    dest: "{{ ar_os_common_dest }}/{{ item | basename }}"
  with_items: "{{ ar_os_common_selection }}"
  when: ar_os_common_selection is defined
