---
- name: "Assertions: ar_os_common (place-registry-cert)"
  assert:
    that: "{{ ar_os_common_cert_assertions }}"

- name: Copy cert file to machines
  copy:
    src: "{{ ar_os_common_cert_path }}"
    dest: "/etc/pki/ca-trust/source/anchors/"
  notify:
    - Update CA trust
    - Restart Docker

- name: Get docker version
  command: 'docker system info --format \{\{.ServerVersion\}\}'
  register: dockerversion
  changed_when: false

- include_tasks: place-docker-certs.yml
  when: dockerversion.stdout is version(ar_os_common_docker_version_1_13, '<')
