---
- name: "Assertions: ar_os_common (place-docker-cert)"
  assert:
    that: "{{ ar_os_common_cert_assertions }}"

- set_fact:
    cert_host_ip: "{{ lookup('dig', '{{ ar_os_common_cert_host }}.')}}"

- name: Update Docker Certs - mkdir
  file:
    path: "/etc/docker/certs.d/{{ ar_os_common_item }}"
    state: directory
  with_items:
    - "{{ cert_host_ip }}"
    - "{{ ar_os_common_cert_host }}:{{ ar_os_common_cert_port }}"
  when: dockerinfo.host_info.ServerVersion is version(ar_os_common_docker_version_1_13, '<')
  loop_control:
    loop_var: ar_os_common_item

- name: Update Docker Certs - copy cert
  copy:
    src: "{{ ar_os_common_cert_path }}"
    dest: "/etc/docker/certs.d/{{ ar_os_common_item }}"
  with_items:
    - "{{ cert_host_ip }}"
    - "{{ ar_os_common_cert_host }}:{{ ar_os_common_cert_port }}"
  when: dockerinfo.host_info.ServerVersion is version(ar_os_common_docker_version_1_13, '<')
  loop_control:
    loop_var: ar_os_common_item
  notify:
    - Restart Docker
