---
- set_fact:
    cert_host_ip: "{{ lookup('dig', '{{ ar_os_common_cert_host }}.')}}"

- debug: var=cert_host_ip

- name: Copy cert file to machines
  copy:
    src: "{{ ar_os_common_cert_path }}"
    dest: "/etc/pki/ca-trust/source/anchors/"
  notify:
    - Update CA trust
    - Restart Docker

- name: Get docker version
  command: 'docker system info --format \{\{.ServerVersion\}\}'
  register: dockerversion
  changed_when: false

- include_tasks: place-docker-certs
  when: dockerversion.stdout is version(ar_os_common_docker_version_1_13, '<')
