---
- name: Check if secret already exists
  shell: oc get secret -n {{ ar_os_common_registry_secret_namespace }} -o jsonpath='{.items[*].metadata.name}'
  register: secret_stat
  changed_when: false
  failed_when: false

- name: Set Fact Docker Password - from password
  set_fact:
    _ar_os_common_docker_password: "{{ ar_os_common_registry_password }}"
  when: ar_os_common_registry_password is defined and ar_os_common_registry_password != ''

- name: Set Fact Docker Password - from token
  set_fact:
    _ar_os_common_docker_password: "{{ ar_os_common_registry_token }}"
  when: ar_os_common_registry_token is defined and ar_os_common_registry_token != ''

- name: Set Fact Service Account and pull operation
  set_fact:
    _ar_os_common_docker_operation: 'pull'
    _ar_os_common_serivce_account: 'default'
  when: ar_os_common_registry_operation is not defined or ar_os_common_registry_operation != 'push'

- name: Set Fact Service Account and push operation
  set_fact:
    _ar_os_common_docker_operation: 'pull,mount'
    _ar_os_common_serivce_account: 'builder'
  when: ar_os_common_registry_operation is defined and ar_os_common_registry_operation == 'push'

- name: Create the secret
  command: oc create secret docker-registry {{ ar_os_common_registry_secret_name }} \
    -n {{ ar_os_common_registry_secret_namespace }}
    --docker-server={{ ar_os_common_registry_server }} \
    --docker-username={{ ar_os_common_registry_username }} \
    --docker-password={{ _ar_os_common_docker_password }} \
    --docker-email={{ ar_os_common_registry_email | default('') }}
  when: ar_os_common_registry_secret_name not in secret_stat.stdout_lines[0].split(' ')

- name: Associate secret as {{ _ar_os_common_docker_operation }} secret for {{ _ar_os_common_serivce_account }} user in {{ ar_os_common_registry_secret_namespace }}
  command: oc secrets link -n {{ ar_os_common_registry_secret_namespace }} {{ _ar_os_common_serivce_account }} {{ ar_os_common_registry_secret_name }} --for={{ _ar_os_common_docker_operation }}
  when: ar_os_common_registry_secret_name not in secret_stat.stdout_lines[0].split(' ')
